version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=impreisonArte
      - DB_USER=postgres
      - DB_PASSWORD=hola123
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: impreisonArte
      POSTGRES_USER: hola123
      POSTGRES_PASSWORD: mipassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
